package com.java.common;

public enum PageType {
	USER_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	VIDEO_MANAGEMENT_PAGE,
	WEB_HOME_PAGE,
	WEB_LOGIN_PAGE,
	WEB_REGISTRATION_PAGE,
	WEB_EDIT_PROFILE_PAGE,
	WEB_CHANGE_PASSWORD_PAGE,
	WEB_FORGOT_PASSWORD_PAGE,
	WEB_VIDEO_DETAIL_PAGE,
	WEB_FAVORITE_PAGE,
	WEB_SHARE_PAGE
	
}
